AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'examples/**/*'
    - 'spec/**/*'
    - 'sig/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - '*.gemspec'
    - 'Rakefile'
    - 'Gemfile'
    - 'idea.rb'

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
